services:
  db:
    image: postgres:15.4
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432" 
  broker:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"